// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mail

import (
	"github.com/YunosukeY/kind-backend/internal/mail/repository"
	"github.com/YunosukeY/kind-backend/internal/util"
)

// Injectors from wire.go:

func initializeController(service string) (controller, func()) {
	tracer, cleanup := util.NewTracer(service)
	reader := repository.NewReader()
	queue := repository.NewQueue(tracer, reader)
	mailer := repository.NewMailer(tracer)
	mailController := NewController(tracer, queue, mailer)
	return mailController, func() {
		cleanup()
	}
}

func initializeDummyController(service string) (controller, func()) {
	tracer, cleanup := util.NewTracer(service)
	queue := repository.NewDummyQueue(tracer)
	mailer := repository.NewDummyMailer(tracer)
	mailController := NewController(tracer, queue, mailer)
	return mailController, func() {
		cleanup()
	}
}
