// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/YunosukeY/kind-backend/internal/util"
)

// Injectors from wire.go:

func initializeRouter(service string) (router, func()) {
	tracer, cleanup := util.NewTracer(service)
	db := newDB()
	appRepository := newRepository(tracer, db)
	writer := newWriter()
	appQueue := newQueue(tracer, writer)
	appController := newController(tracer, appRepository, appQueue)
	appRouter := newRouter(appController)
	return appRouter, func() {
		cleanup()
	}
}

func initializeDummyRouter(service string) (router, func()) {
	tracer, cleanup := util.NewTracer(service)
	appRepository := newDummyRepository(tracer)
	appQueue := newDummyQueue(tracer)
	appController := newController(tracer, appRepository, appQueue)
	appRouter := newRouter(appController)
	return appRouter, func() {
		cleanup()
	}
}
