name: build backend
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: kimitsu
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: kimitsu/kind-backend
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
