name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19.x'
      - run: |
          cat <<EOF > .env
          MYSQL_ROOT_PASSWORD=root
          MYSQL_DATABASE=sample_db
          MYSQL_USER=user1
          MYSQL_PASSWORD=password1
          REDIS_PASSWORD=redis-stack
          EOF
          docker compose up -d db
          ./script/ci.sh run
