name: e2e
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  e2e:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19.x'
      - run: |
          cat <<EOF > .env
          MYSQL_ROOT_PASSWORD=root
          MYSQL_DATABASE=sample_db
          MYSQL_USER=user1
          MYSQL_PASSWORD=password1
          REDIS_PASSWORD=redis-stack
          EOF
          ./script/e2e.sh run
          ./script/e2e.sh down
          ./script/e2e.sh run_grpc
