name: e2e
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  e2e:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - run: |
          cat <<EOF > .env
          MYSQL_ROOT_PASSWORD=root
          MYSQL_DATABASE=sample_db
          MYSQL_USER=user1
          MYSQL_PASSWORD=password1
          REDIS_PASSWORD=redis-stack
          EOF
          ./script/e2e.sh run
          ./script/e2e.sh down
          ./script/e2e.sh run_grpc
