name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  golangci-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: aquaproj/aqua-installer@v3.1.0
        with:
          aqua_version: v2.40.0
      - run: golangci-lint run
